# Generated by Django 3.2.4 on 2021-07-08 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shops', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitedshop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.AddField(
            model_name='searchedcontent',
            name='account_guest',
            field=models.ManyToManyField(blank=True, related_name='searchedContent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preference',
            name='account_guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userPreference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundata',
            name='account_guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userFunData', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountguest',
            name='dislike_shop',
            field=models.ManyToManyField(blank=True, related_name='dislikeShop', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='accountguest',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='accountguest',
            name='like_category',
            field=models.ManyToManyField(blank=True, related_name='likeCategory', to='shops.Category'),
        ),
        migrations.AddField(
            model_name='accountguest',
            name='like_shop',
            field=models.ManyToManyField(blank=True, related_name='likeShop', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='accountguest',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='accountguest',
            name='visited_shop',
            field=models.ManyToManyField(blank=True, related_name='userVisitedStore', through='accounts.VisitedShop', to='shops.Shop'),
        ),
    ]
