# Generated by Django 3.2.4 on 2021-07-07 02:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('shops', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountguest',
            name='like_category',
            field=models.ManyToManyField(blank=True, related_name='likeCategory', to='shops.Category'),
        ),
        migrations.AddField(
            model_name='accountguest',
            name='like_shop',
            field=models.ManyToManyField(blank=True, related_name='likeShop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountguest',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
