# Generated by Django 3.2.4 on 2021-07-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchedarea',
            old_name='name',
            new_name='area',
        ),
    ]
