# Generated by Django 3.2.4 on 2021-07-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_name_searchedarea_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountguest',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
