# Generated by Django 3.2.4 on 2021-07-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accountguest_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountguest',
            name='subscribe_time',
            field=models.DateTimeField(null=True),
        ),
    ]
