# Generated by Django 3.2.4 on 2021-07-05 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountShopkeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('marker_path', models.CharField(max_length=50)),
                ('like_count', models.IntegerField()),
                ('like_user', models.ManyToManyField(blank=True, related_name='likeCategory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shop_description', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('open_time', models.TimeField()),
                ('img_url', models.TextField()),
                ('like_count', models.IntegerField()),
                ('shop_info_url', models.TextField()),
                ('star_score', models.IntegerField()),
                ('is_subscribe', models.BooleanField(default=False)),
                ('subscribe_time', models.DateField()),
                ('area', models.CharField(max_length=20)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.category')),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.coupon')),
                ('like_user', models.ManyToManyField(blank=True, related_name='likeShop', to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.menu')),
                ('shopkeeper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.accountshopkeeper')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_taste', models.IntegerField()),
                ('score_service', models.IntegerField()),
                ('score_cleanliness', models.IntegerField()),
                ('score_vibe', models.IntegerField()),
                ('score_price', models.IntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
                ('writer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='guestReview', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ManyToManyField(blank=True, related_name='ingredients', to='shops.Menu')),
            ],
        ),
    ]
