# Generated by Django 3.2.4 on 2021-07-14 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('content', models.TextField(blank=True)),
                ('public', models.BooleanField(default=True)),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('top_fixed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProposeGoodShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('shop_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='EmailQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=75)),
                ('kind', models.CharField(blank=True, max_length=10)),
                ('title', models.CharField(blank=True, max_length=30)),
                ('content', models.TextField(blank=True)),
                ('img_url_1', models.TextField(blank=True)),
                ('img_url_2', models.TextField(blank=True)),
                ('img_url_3', models.TextField(blank=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=30)),
                ('business_img', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('open_time', models.TextField(blank=True)),
                ('representitive_menu', models.CharField(blank=True, max_length=20)),
                ('img_url_1', models.TextField(blank=True)),
                ('img_url_2', models.TextField(blank=True)),
                ('img_url_3', models.TextField(blank=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.category')),
                ('guest', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='guestBusiness', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
